-- ARCH-10: declare money/quantity columns as DECIMAL(20,6) and FX/exchange-rate columns
-- as DECIMAL(20,10), replacing the implicit NUMERIC(65,30). The chosen scales exceed
-- roundMoney's output (currency minor units, <=4dp) and any realistic FX-rate precision,
-- so no stored value is rounded (verified against seed data: max significant scale was 1dp,
-- and the migration was value-diff checked before commit).

-- AlterTable
ALTER TABLE "BankReconciliation" ALTER COLUMN "statementBalance" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "clearedBalance" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "BankStatement" ALTER COLUMN "openingBalance" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "closingBalance" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "BankStatementLine" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "runningBalance" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "BankTransfer" ALTER COLUMN "fromAmount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "toAmount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10);

-- AlterTable
ALTER TABLE "BillPaymentAllocation" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "Budget" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "BudgetLine" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "Campaign" ALTER COLUMN "plannedBudget" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "actualSpend" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "CampaignMetric" ALTER COLUMN "value" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "CreditNote" ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountApplied" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountRemaining" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "totalBase" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "CreditNoteApplication" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "CreditNoteLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "lineNet" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxAmount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "creditLimit" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "CustomerReceipt" ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "allocatedAmount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unappliedAmount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountBase" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "ExchangeRate" ALTER COLUMN "rate" SET DATA TYPE DECIMAL(20,10);

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxAmount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountPaid" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "JournalEntry" ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "totalCreditBase" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "totalDebitBase" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "JournalLine" ALTER COLUMN "debit" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "credit" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "transactionAmount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "ReceiptAllocation" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SalesInvoice" ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountPaid" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountDue" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "totalBase" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SalesInvoiceLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "discountPct" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "lineNet" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxAmount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "StorePerformance" ALTER COLUMN "sales" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "refunds" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "aov" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "conversionRate" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "adSpend" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "discounts" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "shippingCost" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "cogs" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "grossMargin" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "netContribution" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "netSales" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "cost" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SupplierBill" ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountPaid" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountDue" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "totalBase" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SupplierBillLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "discountPct" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "lineNet" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxAmount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SupplierCredit" ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxTotal" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountApplied" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountRemaining" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "totalBase" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SupplierCreditApplication" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SupplierCreditLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "lineNet" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "taxAmount" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "SupplierPayment" ALTER COLUMN "exchangeRate" SET DATA TYPE DECIMAL(20,10),
ALTER COLUMN "amount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "allocatedAmount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "unappliedAmount" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "amountBase" SET DATA TYPE DECIMAL(20,6);

-- AlterTable
ALTER TABLE "TaxRate" ALTER COLUMN "rate" SET DATA TYPE DECIMAL(20,6);
